### ISSUE TITLE
[RFC] Presets

### ISSUE THREAD

**Issue by gausie** [loathers/greenbox#62]
I'm proposing a set of shareable filter "presets" that make it possible to view a greenbox profile showing only the boxen that are important for a specific scope.

Proposed Implementation
==

A new package would be added to the repository with the following structure

```
.
└── packages/
    └── greenbox-presets/
        ├── package.json
        ├── garbo.yml
        ├── standard23.yml
        └── hccs70.yml
```

These yml files are formatted like this

```yml
version: 1 # Just so we can change this file's structure if necessary
name: Preset name
description: |
  Markdown for description
  Multilines or whatever!
items:
  - 104 # For ease of editing this file you could add names for these ids as comments
  - id: 154
    reason: Optional reasons!
    priority: required # "required" and "recommended"?
skills:
  - 55
  - id: 105
    reason: Optional reasons!
  - 7004
```

When viewing a profile, you can add `&p=garbo` (for example) and have the view filtered to only the items and skills specified in the file.
